prgrms-web-devcourse/Team-5YES-WuMo-BE

- src/main/java/org/prgrms/wumo/domain/member/model/Email.java
- src/main/java/org/prgrms/wumo/domain/member/model/Member.java
- src/main/java/org/prgrms/wumo/domain/member/model/Password.java
- 회원 엔티티 구현
- 스프링 시큐리티 공부가 아직 미흡해 엔티티의 수정 가능성이 있습니다!
- Resolved : [WUMO-89], [WUMO-98], [WUMO-99]
[WUMO-89]: https://shoekream.atlassian.net/browse/WUMO-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-98]: https://shoekream.atlassian.net/browse/WUMO-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-99]: https://shoekream.atlassian.net/browse/WUMO-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-7] Member 엔티티 구현

- src/main/java/org/prgrms/wumo/domain/party/model/Invitation.java
- src/main/java/org/prgrms/wumo/domain/party/model/Party.java
- src/main/java/org/prgrms/wumo/domain/party/model/PartyMember.java
- 모임, 모임 구성원, 초대 엔티티 구현
- 엔티티 자체 메서드는 구현되지 않은 상태입니다.
- 서비스 코드 작성에 따라 추가될 수 있습니다.
- Resolved : [WUMO-102], [WUMO-103], [WUMO-104]
[WUMO-102]: https://shoekream.atlassian.net/browse/WUMO-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-103]: https://shoekream.atlassian.net/browse/WUMO-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-104]: https://shoekream.atlassian.net/browse/WUMO-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-8] Party 관련 엔티티 구현

- src/main/java/org/prgrms/wumo/domain/location/model/Location.java
- src/main/java/org/prgrms/wumo/domain/member/model/Member.java
- src/main/java/org/prgrms/wumo/domain/route/model/Route.java
- 루트 엔티티 구현
- 편의를 위해 후보지 임시 엔티티를 구현했습니다!
- Resolved : [WUMO-105]
[WUMO-105]: https://shoekream.atlassian.net/browse/WUMO-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-105] Route 엔티티 구현

- src/main/java/org/prgrms/wumo/domain/comment/model/Comment.java
- src/main/java/org/prgrms/wumo/domain/comment/model/ContentType.java
- src/main/java/org/prgrms/wumo/domain/comment/model/LocationComment.java
- src/main/java/org/prgrms/wumo/domain/comment/model/PrivateRouteComment.java
- src/main/java/org/prgrms/wumo/domain/comment/model/PublicRouteComment.java
- src/main/java/org/prgrms/wumo/domain/location/model/Category.java
- src/main/java/org/prgrms/wumo/domain/location/model/Location.java
Location 관련 엔티티 구현
Comment 관련 엔티티 구현
Location, Category 엔티티 구현
Comment, ContentType, LocationComment, PrivateRouteComment, PublicRouteComment 엔티티 구현
- Resolved : WUMO-9, WUMO-10
> [WUMO-9], [WUMO-10] Comment, Location 관련 엔티티 구현

- src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
- src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberEmailCheckRequest.java
- src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberLoginRequest.java
- src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberNicknameCheckRequest.java
- src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberUpdateRequest.java
- src/main/java/org/prgrms/wumo/domain/member/dto/response/MemberGetResponse.java
- src/main/java/org/prgrms/wumo/domain/member/dto/response/MemberLoginResponse.java
- src/main/java/org/prgrms/wumo/domain/member/dto/response/MemberRegisterResponse.java
- 회원 API 명세서 swagger로 작업
- 비밀번호 찾기 기능은 일단 보류하였습니다!
- Resolved : [WUMO-13]
[WUMO-13]: https://shoekream.atlassian.net/browse/WUMO-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-13] Member API 명세서

- src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java
- src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteGetAllRequest.java
- src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java
- src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetResponse.java
- src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteLocationResponse.java
- src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteRegisterResponse.java
- 루트 API 명세서 swagger로 작업
- 우선순위가 낮아진 좋아요 기능 관련 컬럼들은 일단 주석처리 해두었습니다!
- Resolved : [WUMO-17]
[WUMO-17]: https://shoekream.atlassian.net/browse/WUMO-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-17] Route API 명세서

- src/main/java/org/prgrms/wumo/domain/party/api/InvitationController.java
- src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java
- src/main/java/org/prgrms/wumo/domain/party/api/PartyMemberController.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/InvitationRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyGetRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyJoinRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyMemberGetRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyUpdateRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/InvitationRegisterResponse.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetAllResponse.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetDetailResponse.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetResponse.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyMemberGetAllResponse.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyMemberGetResponse.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyRegisterResponse.java
- 모임(파티) API 명세서 Swagger로 작업
- 같은 도메인에서 관리하도록 패키지 구조를 결정했습니다.
- Resolved : [WUMO-114], [WUMO-115], [WUMO-116]
[WUMO-114]: https://shoekream.atlassian.net/browse/WUMO-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-115]: https://shoekream.atlassian.net/browse/WUMO-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-116]: https://shoekream.atlassian.net/browse/WUMO-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-14] Party API 명세서

- .github/workflows/ci.yml
- develop branch CI
- Resolved : [WUMO-120]
[WUMO-120]: https://shoekream.atlassian.net/browse/WUMO-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-120] develop branch CI 구축

- src/main/java/org/prgrms/wumo/domain/image/api/ImageController.java
- src/main/java/org/prgrms/wumo/domain/image/dto/request/ImageDeleteRequest.java
- src/main/java/org/prgrms/wumo/domain/image/dto/request/ImageRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/image/dto/response/ImageRegisterResponse.java
- 이미지 API 명세서 Swagger로 작업
- 이미지 삭제 경로를 URL Pull Path로 받을 경우 문제가 생길 수 있어 Body로 지정
- Resolved : [WUMO-19]
[WUMO-19]: https://shoekream.atlassian.net/browse/WUMO-19?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-19] Image API 명세서

- .github/workflows/ci-cd.yml
- .github/workflows/ci.yml
- src/main/resources/application-prod.yml
- develop branch CI test
- Resolved : [WUMO-123]
[WUMO-123]: https://shoekream.atlassian.net/browse/WUMO-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-123] develop branch CI test

- src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java
- src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationGetAllRequest.java
- src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationUpdateRequest.java
- src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationGetAllResponse.java
- src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationGetResponse.java
- src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationRegisterResponse.java
후보지 API 문서화
Swagger 이용 후보지 API 문서화
- Resolved : WUMO-16
> [WUMO-16] Location API 명세서

- src/main/resources/logback-spring.xml
- Logback의 Spring Profile 환경에 따른 설정값 반영
- prod, local 만 구분되어 있습니다. (local | !prod 같은 표현식도 가능)
- Resolved : [WUMO-124]
[WUMO-124]: https://shoekream.atlassian.net/browse/WUMO-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-124] Logback Spring Profile 설정

- README.md
Add README.md
Add READM.md v0
- Resolved : WUMO-125
> [WUMO-125] README.md 추가

- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- src/main/resources/db/migration/V1__init.sql
- src/test/java/org/prgrms/wumo/MysqlTestContainer.java
- src/test/resources/application-test.yml
- 테스트 컨테이너 설정
- flyway 설정 yml에서 위치 변경
- Resolved : [WUMO-126], [WUMO-127]
[WUMO-126]: https://shoekream.atlassian.net/browse/WUMO-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-127]: https://shoekream.atlassian.net/browse/WUMO-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-119] TestContainer 설정

- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- src/main/resources/db/migration/V1__init.sql
- Flyway 및 스키마 초기 설정 보완
- 없음
- Resolved : [WUMO-128]
[WUMO-128]: https://shoekream.atlassian.net/browse/WUMO-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-128] Flyway 및 스키마 초기 설정 보완

- build.gradle
- src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
- src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberEmailCheckRequest.java
- src/main/java/org/prgrms/wumo/domain/member/model/Email.java
- src/main/java/org/prgrms/wumo/domain/member/repository/MemberRepository.java
- src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
- src/main/java/org/prgrms/wumo/global/exception/ExceptionResponse.java
- src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java
- src/main/java/org/prgrms/wumo/global/exception/custom/DuplicateException.java
- src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
- src/test/java/org/prgrms/wumo/domain/member/model/EmailTest.java
- src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
- 회원 이메일 중복체크 기능 구현
- flyway dependency 추가
- 이메일 중복체크 정규식을 짜보았는데 같이 체크해주시면 감사하겠습니다 (추천 받습니다!)
- Resolved : [WUMO-129], [WUMO-130], [WUMO-131], [WUMO-132]
[WUMO-129]: https://shoekream.atlassian.net/browse/WUMO-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-130]: https://shoekream.atlassian.net/browse/WUMO-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-131]: https://shoekream.atlassian.net/browse/WUMO-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-132]: https://shoekream.atlassian.net/browse/WUMO-132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-27] Member 이메일 중복체크 기능 구현

- src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java
- src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteStatusUpdateRequest.java
- 루트 공개여부 수정 API 추가
- Resolved : [WUMO-134]
[WUMO-134]: https://shoekream.atlassian.net/browse/WUMO-134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-133] Route API 명세서 보완

- src/main/java/org/prgrms/wumo/domain/party/api/InvitationController.java
- src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java
- src/main/java/org/prgrms/wumo/domain/party/api/PartyMemberController.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyMemberRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyMemberUpdateRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/party/model/Invitation.java
- src/main/java/org/prgrms/wumo/domain/party/model/Party.java
- src/main/java/org/prgrms/wumo/domain/party/model/PartyMember.java
- 모임 생성 및 모임 구성원 관련 API 보완
- 특이사항 없음
- Resolved : [WUMO-140]
[WUMO-140]: https://shoekream.atlassian.net/browse/WUMO-140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-140] Party API 명세서 보완

- src/main/java/org/prgrms/wumo/domain/location/model/Location.java
- src/main/java/org/prgrms/wumo/domain/member/model/Email.java
- src/main/java/org/prgrms/wumo/domain/member/model/Member.java
- src/main/java/org/prgrms/wumo/domain/party/model/Invitation.java
- src/main/java/org/prgrms/wumo/domain/party/model/Party.java
- src/main/java/org/prgrms/wumo/domain/route/model/Route.java
- src/main/resources/application-prod.yml
- src/main/resources/db/migration/V2__alter_location_change_created_at.sql
- 스키마 오타 정정 및 보완
member
- email v 50 (유니크제약조건에도)
- nickname 20 (유니크제약조건에도)
location
- createdAt → created_at
- updatedAt → updated_at
party_route_comment
- id varchar(255) → bigint
comment
- DTYPE -> dtype
- Resolved : [WUMO-139]
[WUMO-139]: https://shoekream.atlassian.net/browse/WUMO-139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-139] 스키마 보완

- build.gradle
- src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
- src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberLoginRequest.java
- src/main/java/org/prgrms/wumo/domain/member/dto/response/MemberLoginResponse.java
- src/main/java/org/prgrms/wumo/domain/member/model/Member.java
- src/main/java/org/prgrms/wumo/domain/member/repository/MemberRepository.java
- src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
- src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java
- src/main/java/org/prgrms/wumo/global/jwt/JwtAuthenticationFilter.java
- src/main/java/org/prgrms/wumo/global/jwt/JwtTokenProvider.java
- src/main/java/org/prgrms/wumo/global/jwt/WumoJwt.java
- src/main/java/org/prgrms/wumo/global/mapper/MemberMapper.java
- src/main/resources/application-prod.yml
- src/main/resources/db/migration/V4__alter_member_add_refresh_token.sql
- src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
- src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
- src/test/resources/application-test.yml
- 회원 로그인 기능 구현
- access token과 refresh token 발급까지는 구현했으나, 토큰 만료 시 재발급 로직은 추후 구현 예정입니다!
- Resolved : [WUMO-142], [WUMO-143], [WUMO-146], [WUMO-148]
[WUMO-142]: https://shoekream.atlassian.net/browse/WUMO-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-143]: https://shoekream.atlassian.net/browse/WUMO-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-146]: https://shoekream.atlassian.net/browse/WUMO-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-148]: https://shoekream.atlassian.net/browse/WUMO-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-29] Member 로그인 기능 구현

- .gitignore
- src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
- src/main/java/org/prgrms/wumo/domain/member/model/Member.java
- src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
- src/main/java/org/prgrms/wumo/global/jwt/JwtTokenProvider.java
- src/test/java/org/prgrms/wumo/domain/member/model/EmailTest.java
- 회원 로그아웃 기능 구현
- access token 만료시간 10분으로 수정
- 로그아웃 기능 테스트가 불필요하다고 생각해 진행하지 않았습니다
- access token 삭제가 불가능해 만료시간을 30분에서 10분으로 더 짧게 설정하였습니다
- Resolved : [WUMO-149]
[WUMO-149]: https://shoekream.atlassian.net/browse/WUMO-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-30] Member 로그아웃 기능 구현

- src/main/java/org/prgrms/wumo/global/config/JwtConfig.java
- src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java
- src/main/java/org/prgrms/wumo/global/jwt/JwtTokenProvider.java
- 타입 안정성을 위해 properties 값을 properties class로 정의 후 주입
- Resolved : [WUMO-152], [WUMO-153]
[WUMO-152]: https://shoekream.atlassian.net/browse/WUMO-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-153]: https://shoekream.atlassian.net/browse/WUMO-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-151] Member properties 값 주입 리팩토링

- src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java
- src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/location/model/Location.java
- src/main/java/org/prgrms/wumo/domain/location/repository/LocationRepository.java
- src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java
- src/main/java/org/prgrms/wumo/global/mapper/LocationMapper.java
- src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
- src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
Location 등록 기능 구현
Location 등록 기능 구현 및 테스트 코드 작성
- Resolved : WUMO-37
> [WUMO-37] Location 등록 기능 구현

- src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java
- src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationGetResponse.java
- src/main/java/org/prgrms/wumo/domain/location/model/Location.java
- src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java
- src/main/java/org/prgrms/wumo/global/mapper/LocationMapper.java
- src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
- src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
Location 상세 조회 기능 구현 및 테스트
추후 Route 코드 구현 시, route id 가져오는 코드 추가할 예정
- Resolved : WUMO-45
> [WUMO-45] Location 상세 조회 기능 구현

- src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java
- src/main/java/org/prgrms/wumo/global/exception/custom/CustomAccessDeniedHandler.java
- src/main/java/org/prgrms/wumo/global/exception/custom/CustomAuthenticationEntryPoint.java
- 인증, 인가 관련 예외 구현 및 예외 핸들링
- Resolved : [WUMO-166], [WUMO-167], [WUMO-168]
[WUMO-166]: https://shoekream.atlassian.net/browse/WUMO-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-167]: https://shoekream.atlassian.net/browse/WUMO-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-168]: https://shoekream.atlassian.net/browse/WUMO-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-165] Security 인증, 인가 관련 예외 구현 및 핸들링

- src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
- src/main/java/org/prgrms/wumo/domain/member/dto/response/MemberGetResponse.java
- src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
- src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java
- src/main/java/org/prgrms/wumo/global/jwt/JwtTokenProvider.java
- src/main/java/org/prgrms/wumo/global/jwt/JwtUtil.java
- src/main/java/org/prgrms/wumo/global/mapper/MemberMapper.java
- src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
- src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
- 내 정보 조회 기능 구현 및 테스트
- 현재 로그인 중인 회원의 아이디를 authentication 객체에서 가져오는 로직이 추가되었습니다
JwtUtil을 참고해서 사용해주세요!
- Resolved : [WUMO-170], [WUMO-171], [WUMO-172]
[WUMO-170]: https://shoekream.atlassian.net/browse/WUMO-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-171]: https://shoekream.atlassian.net/browse/WUMO-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-172]:https://shoekream.atlassian.net/browse/WUMO-172
[WUMO-172]: https://shoekream.atlassian.net/browse/WUMO-172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-172]: https://shoekream.atlassian.net/browse/WUMO-172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …
> [WUMO-169] Member 내 정보 조회 기능 구현

- src/main/java/org/prgrms/wumo/domain/party/api/InvitationController.java
- src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java
- src/main/java/org/prgrms/wumo/domain/party/api/PartyMemberController.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyMemberRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java
- src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
- src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
- src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java
- src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java
- src/test/java/org/prgrms/wumo/domain/party/api/PartyMemberControllerTest.java
- src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java
- src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
- src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
- 모임 구성원(PartyMember) 등록 기능 구현 및 테스트
- 특이사항 없음
- Resolved : [WUMO-186], [WUMO-187]
- Trouble Shooting : [컨트롤러 테스트 중 Transaciton 관련 이슈](https://www.notion.so/backend-devcourse/Transaciton-345c9ab15c284a26b1c3ca0b8897e5aa?pvs=4).
[WUMO-186]: https://shoekream.atlassian.net/browse/WUMO-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-187]: https://shoekream.atlassian.net/browse/WUMO-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-41] PartyMember 등록 기능 구현

- src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java
- src/main/java/org/prgrms/wumo/domain/route/model/Route.java
- src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
- src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
- src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
- 루트 공개여부 변경 기능 구현 및 테스트
- 특이사항은 없습니다!
- Resolved : [WUMO-189], [WUMO-190]
[WUMO-189]: https://shoekream.atlassian.net/browse/WUMO-189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-190]: https://shoekream.atlassian.net/browse/WUMO-190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-56] Route 공개여부 변경 기능 구현

- src/main/java/org/prgrms/wumo/domain/party/api/PartyMemberController.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyMemberGetAllResponse.java
- src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepository.java
- src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepositoryImpl.java
- src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java
- src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java
- src/test/java/org/prgrms/wumo/domain/party/api/PartyMemberControllerTest.java
- src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java
- PartyMember 조회 기능 구현 및 테스트
- QueryDSL 사용하는 Repo 구현체에서 내부적으로 메서드를 통합했는데 해당 부분 봐주시면 감사하겠습니다.
- (참고) private ... findAllByColumnId()
- Resolved : [WUMO-191], [WUMO-192]
[WUMO-191]: https://shoekream.atlassian.net/browse/WUMO-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-192]: https://shoekream.atlassian.net/browse/WUMO-192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-43] PartyMember 조회 기능 구현

- src/main/java/org/prgrms/wumo/domain/comment/api/LocationCommentController.java
- src/main/java/org/prgrms/wumo/domain/comment/dto/request/LocationCommentRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/comment/model/Comment.java
- src/main/java/org/prgrms/wumo/domain/comment/model/LocationComment.java
- src/main/java/org/prgrms/wumo/domain/comment/model/PartyRouteComment.java
- src/main/java/org/prgrms/wumo/domain/comment/repository/LocationCommentRepository.java
- src/main/java/org/prgrms/wumo/domain/comment/service/LocationCommentService.java
- src/main/java/org/prgrms/wumo/global/mapper/CommentMapper.java
- src/test/java/org/prgrms/wumo/domain/comment/api/LocationCommentControllerTest.java
- src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java
- src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
Builder BugFix
LocationComment 등록 기능 구현 및 테스트
- Resolved : WUMO-79, WUMO-188
> [WUMO-79] LocationComment 등록 기능 구현

- src/main/java/org/prgrms/wumo/domain/party/api/PartyMemberController.java
- src/main/java/org/prgrms/wumo/domain/party/model/PartyMember.java
- src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepository.java
- src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepositoryImpl.java
- src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java
- src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java
- src/test/java/org/prgrms/wumo/domain/party/api/PartyMemberControllerTest.java
- src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java
- PartyMember 수정 기능 구현 및 테스트
- 역할 외 수정될 요구사항이 없어서 역할만 수정되게 구현했습니다!
- Resolved : [WUMO-193], [WUMO-194]
[WUMO-193]: https://shoekream.atlassian.net/browse/WUMO-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-194]: https://shoekream.atlassian.net/browse/WUMO-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-42] PartyMember 수정 기능 구현

- src/main/java/org/prgrms/wumo/domain/comment/api/LocationCommentController.java
- src/main/java/org/prgrms/wumo/domain/comment/dto/request/LocationCommentGetAllRequest.java
- src/main/java/org/prgrms/wumo/domain/comment/dto/response/LocationCommentGetAllResponse.java
- src/main/java/org/prgrms/wumo/domain/comment/dto/response/LocationCommentGetResponse.java
- src/main/java/org/prgrms/wumo/domain/comment/repository/LocationCommentCustomRepository.java
- src/main/java/org/prgrms/wumo/domain/comment/repository/LocationCommentCustomRepositoryImpl.java
- src/main/java/org/prgrms/wumo/domain/comment/repository/LocationCommentRepository.java
- src/main/java/org/prgrms/wumo/domain/comment/service/LocationCommentService.java
- src/main/java/org/prgrms/wumo/global/mapper/CommentMapper.java
- src/test/java/org/prgrms/wumo/domain/comment/api/LocationCommentControllerTest.java
- src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java
후보지 댓글 목록 조회 기능 구현 및 테스트
- Resolved : WUMO-88
> [WUMO-88] 후보지 댓글 목록 조회 기능 구현

- src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java
- src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java
- src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponses.java
- src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteLocationSimpleResponse.java
- src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepository.java
- src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepositoryImpl.java
- src/main/java/org/prgrms/wumo/domain/route/repository/RouteRepository.java
- src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
- src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java
- src/main/java/org/prgrms/wumo/global/mapper/MemberMapper.java
- src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java
- src/main/resources/db/migration/V5__alter_route_add_desc_index.sql
- src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
- src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
- 공개된 루트 목록 조회 기능 구현 및 테스트
- Dto 참고사항) 전체 응답이 루트 목록을 가지고있고
루트 목록에서의 각각의 루트는 장소 목록을 가지고 있습니다
- Resolved : [WUMO-195], [WUMO-196]
[WUMO-195]: https://shoekream.atlassian.net/browse/WUMO-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-196]: https://shoekream.atlassian.net/browse/WUMO-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-57] Route 목록 조회 기능 구현

- src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java
- Spring Security에서 cors 활성화
- Resolved : [WUMO-201]
[WUMO-201]: https://shoekream.atlassian.net/browse/WUMO-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-200] Security CORS 활성화

- src/main/resources/application-prod.yml
- 서버 포트 변경 (8080 -> 80)
- 도메인에 노출되는 포트(8080)를 가리기 위해 80 포트로 변경
- Resolved : [WUMO-203]
[WUMO-203]: https://shoekream.atlassian.net/browse/WUMO-203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-203] Server port 변경

- src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java
- src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationSpendingUpdateRequest.java
- src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationSpendingUpdateResponse.java
Location 실제 사용 금액 갱신 API 추가
- Resolved : WUMO-205
> [WUMO-205] Location API 명세서 보완

- src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
- src/main/java/org/prgrms/wumo/domain/member/model/Member.java
- src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
- src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
- src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
- 회원 내 정보 수정 기능 구현 및 테스트
- 특이사항 없습니다
- Resolved : [WUMO-206], [WUMO-207]
[WUMO-206]: https://shoekream.atlassian.net/browse/WUMO-206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-207]: https://shoekream.atlassian.net/browse/WUMO-207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-33] Member 내 정보 수정 기능 구현

- deploy.sh
- nginx/nginx.conf
- nginx/wumo.conf
- src/main/resources/application-prod.yml
- NGinx & SSL 인증서 적용
- deploy.sh 을 통해 해당 파일이 복사 및 NGinx 재실행되는 과정은 서버에 NGinx가 있다고 가정한 상태입니다.
- Resolved : [WUMO-213]
[WUMO-213]: https://shoekream.atlassian.net/browse/WUMO-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-213] NGinx & SSL 인증서 적용

- src/main/java/org/prgrms/wumo/domain/comment/api/RouteCommentController.java
- src/main/java/org/prgrms/wumo/domain/comment/dto/request/PartyRouteCommentGetAllRequest.java
- src/main/java/org/prgrms/wumo/domain/comment/dto/response/LocationCommentGetResponse.java
- src/main/java/org/prgrms/wumo/domain/comment/dto/response/PartyRouteCommentGetAllResponse.java
- src/main/java/org/prgrms/wumo/domain/comment/dto/response/PartyRouteCommentGetResponse.java
- src/main/java/org/prgrms/wumo/domain/comment/repository/PartyRouteCommentCustomRepository.java
- src/main/java/org/prgrms/wumo/domain/comment/repository/PartyRouteCommentCustomRepositoryImpl.java
- src/main/java/org/prgrms/wumo/domain/comment/repository/PartyRouteCommentRepository.java
- src/main/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentService.java
- src/main/java/org/prgrms/wumo/global/mapper/CommentMapper.java
- src/test/java/org/prgrms/wumo/domain/comment/api/PartyRouteCommentControllerTest.java
- src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
PartyRouteComment 목록 조회 기능 구현
LocationComment 와 기능이 거의 유사합니다
- Resolved : WUMO-80
> [WUMO-80] PartyRouteComment 목록 조회 기능 구현

- src/main/java/org/prgrms/wumo/domain/party/api/InvitationController.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/InvitationRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/InvitationRegisterResponse.java
- src/main/java/org/prgrms/wumo/domain/party/model/Invitation.java
- src/main/java/org/prgrms/wumo/domain/party/repository/InvitationRepository.java
- src/main/java/org/prgrms/wumo/domain/party/service/InvitationService.java
- src/main/java/org/prgrms/wumo/global/base62/Base62Util.java
- src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java
- src/main/resources/db/migration/V7__alter_invitation_drop_code.sql
- src/test/java/org/prgrms/wumo/domain/party/api/InvitationControllerTest.java
- src/test/java/org/prgrms/wumo/domain/party/service/InvitationServiceTest.java
- Invitation 등록(발급) 기능 구현 및 테스트
- Encode, Decode 관련 로직 한 번 리뷰 부탁드립니다!
- 만료되지 않은 초대장은 신규 발급 없이 재사용하도록 정책을 확정했습니다.
- Resolved : [WUMO-222], [WUMO-223]
[WUMO-222]: https://shoekream.atlassian.net/browse/WUMO-222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-223]: https://shoekream.atlassian.net/browse/WUMO-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-49] Invitation 등록(발급) 기능 구현

- .github/workflows/ci-cd.yml
- CD 시 로그 충돌 문제 수정
- CI 과정에서 발생한 로그는 필요하지 않기 때문에 정상적으로 빌드 후에 삭제하도록 수정
- Resolved : [WUMO-220]
[WUMO-220]: https://shoekream.atlassian.net/browse/WUMO-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-220] CD 시 로그 충돌 문제 수정

- src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteGetAllRequest.java
- src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java
- src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepository.java
- src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepositoryImpl.java
- src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
- src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java
- src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
- src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
- 검색 지역에 위치한 후보지가 포함된 루트 검색 기능 구현 및 테스트
- 추후 성능 개선 예정입니다!
- Resolved : [WUMO-227], [WUMO-228]
[WUMO-227]: https://shoekream.atlassian.net/browse/WUMO-227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-228]: https://shoekream.atlassian.net/browse/WUMO-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-62] Route 지역 기준 검색 기능 구현

- src/main/java/org/prgrms/wumo/domain/image/dto/request/ImageDeleteRequest.java
- src/main/java/org/prgrms/wumo/domain/image/dto/request/ImageRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/image/dto/response/ImageRegisterResponse.java
- src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberEmailCheckRequest.java
- src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberLoginRequest.java
- src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberNicknameCheckRequest.java
- src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberUpdateRequest.java
- src/main/java/org/prgrms/wumo/domain/member/dto/response/MemberGetResponse.java
- src/main/java/org/prgrms/wumo/domain/member/dto/response/MemberLoginResponse.java
- src/main/java/org/prgrms/wumo/domain/member/dto/response/MemberRegisterResponse.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/InvitationRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteGetAllRequest.java
- src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteStatusUpdateRequest.java
- src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java
- src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponses.java
- src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetResponse.java
- src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteLocationResponse.java
- src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteLocationSimpleResponse.java
- src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteRegisterResponse.java
- src/main/java/org/prgrms/wumo/domain/route/model/Route.java
- src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java
- src/main/resources/db/migration/V8__alter_route_add_like_count.sql
- 좋아요 기능이 추가됨에 따라 루트 API 명세서에 요구사항 변경 반영
- 루트 엔티티에 좋아요수 필드가 추가되었습니다
- Resolved : [WUMO-231], [WUMO-232]
[WUMO-231]: https://shoekream.atlassian.net/browse/WUMO-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-232]: https://shoekream.atlassian.net/browse/WUMO-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-230] Route API 명세서에 요구사항 변경 반영

- src/main/java/org/prgrms/wumo/domain/like/controller/RouteLikeController.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyGetRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyMemberGetRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyMemberRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyMemberUpdateRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyUpdateRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/InvitationRegisterResponse.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/InvitationValidateResponse.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetAllResponse.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetResponse.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyMemberGetAllResponse.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyMemberGetResponse.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyRegisterResponse.java
- RouteLike API 명세서 추가
- Party API 명세서 RequiredMode 수정
- 신규 API 명세서 추가와 동시에 기존에 required를 사용하던 나머지 부분을 보완했습니다.
- Resolved : [WUMO-229]
[WUMO-229]: https://shoekream.atlassian.net/browse/WUMO-229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-229] RouteLike API 명세서 추가

- src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java
- src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java
- src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
- src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
Location 삭제 기능 구현 및 테스트
단순 삭제 기능입니다!
- Resolved : WUMO-234, WUMO-235
> [WUMO-48] Location 삭제 기능 구현

- src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java
- src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationGetAllRequest.java
- src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationSpendingUpdateRequest.java
- src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationUpdateRequest.java
- src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationGetAllResponse.java
- src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationGetResponse.java
- src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationRegisterResponse.java
- src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationSpendingUpdateResponse.java
- src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationUpdateResponse.java
Location 명세서 용어 통일 및 Required 수정
- Resolved : WUMO-243
> [WUMO-242] Location API 명세서 형식 정리

- src/main/java/org/prgrms/wumo/domain/image/service/ImageService.java
- src/test/java/org/prgrms/wumo/domain/image/api/ImageControllerTest.java
- Image 삭제 중 도메인 검증 로직 추가 및 테스트
- 현재 필수적인 기능은 아니나 삭제 기능이 완료되어감에 따라 로직 보완이 필요하다고 판단했습니다.
- Resolved : [WUMO-262], [WUMO-263]
[WUMO-262]: https://shoekream.atlassian.net/browse/WUMO-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-263]: https://shoekream.atlassian.net/browse/WUMO-263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-261] Image 삭제 중 도메인 검증 로직 추가

- src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java
- src/main/resources/application-prod.yml
- src/test/resources/application-test.yml
CORS 에러 다시 발생
- OPTIONS 허용
- Cors Origin에 프론트 서버 추가
- Resolved : [WUMO-282]
[WUMO-282]: https://shoekream.atlassian.net/browse/WUMO-282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-282] Preflight 설정 변경 및 Cors Origin에 프론트 서버 추가

- src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberUpdateRequest.java
- src/main/java/org/prgrms/wumo/domain/member/model/Member.java
- 비밀번호를 수정하지 않았다면 원래 비밀번호 사용하도록 구현
- Resolved : [WUMO-285]
[WUMO-285]: https://shoekream.atlassian.net/browse/WUMO-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-280] Member 내 정보 수정 기능 리팩토링

- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyType.java
- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyUpdateRequest.java
- src/main/java/org/prgrms/wumo/domain/party/model/Party.java
- src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
- src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java
- src/main/resources/db/migration/V13__alter_party_drop_password.sql
- src/test/java/org/prgrms/wumo/domain/comment/api/LocationCommentControllerTest.java
- src/test/java/org/prgrms/wumo/domain/comment/api/PartyRouteCommentControllerTest.java
- src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java
- src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
- src/test/java/org/prgrms/wumo/domain/like/controller/RouteLikeControllerTest.java
- src/test/java/org/prgrms/wumo/domain/like/service/RouteLikeServiceTest.java
- src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
- src/test/java/org/prgrms/wumo/domain/party/api/InvitationControllerTest.java
- src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java
- src/test/java/org/prgrms/wumo/domain/party/api/PartyMemberControllerTest.java
- src/test/java/org/prgrms/wumo/domain/party/model/PartyTest.java
- src/test/java/org/prgrms/wumo/domain/party/service/InvitationServiceTest.java
- src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java
- src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
- Party 스키마 삭제 및 DTO 예외 추가
- PASSWORD 관련 필드는 MVP에 포함되지 않고 기능 개발이 추가적으로 이루어지지 않을 예정이므로 삭제
- Resolved : [WUMO-290]
[WUMO-290]: https://shoekream.atlassian.net/browse/WUMO-290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-290] Party 스키마 및 DTO 수정

- src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java
- src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetResponse.java
- src/main/java/org/prgrms/wumo/domain/party/repository/InvitationRepository.java
- src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepositoryImpl.java
- src/main/java/org/prgrms/wumo/domain/party/service/InvitationService.java
- src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java
- src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
- src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java
- src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java
- src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
- Party 조회시 fetchJoin 문제 수정 및 기타 미수정된 부분 정리
- 이전 PR 때 체크하지 못 한 DTO 부분들이 있어서 같이 반영했습니다.
- Resolved : [WUMO-314], [WUMO-315]
[WUMO-314]: https://shoekream.atlassian.net/browse/WUMO-314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-315]: https://shoekream.atlassian.net/browse/WUMO-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-313] Party 조회시 fetchJoin 문제 수정

- src/main/resources/application-prod.yml
-  데이터베이스 Batch 관련 옵션 추가
- 특이사항 없음
- Resolved : [WUMO-331]
[WUMO-331]: https://shoekream.atlassian.net/browse/WUMO-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-331] YML - 데이터베이스 Batch 관련 옵션 추가

- src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
- src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
- src/main/java/org/prgrms/wumo/global/config/AsyncConfig.java
- src/main/java/org/prgrms/wumo/global/config/WebConfig.java
- src/main/java/org/prgrms/wumo/global/event/MemberCreateEvent.java
- src/main/java/org/prgrms/wumo/global/event/listener/MemberEventListener.java
- src/main/java/org/prgrms/wumo/global/repository/RedisRepository.java
- src/main/java/org/prgrms/wumo/global/sender/EmailSender.java
- src/main/java/org/prgrms/wumo/global/sender/Sender.java
- src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
- 회원가입 축하 메일 전송 기능 구현
- 트랜잭션이 끝난 후 메일이 전송되도록 이벤트 처리 하였습니다
- 이 때, 비동기로 전송되도록 구현하였습니다
- Resolved : [WUMO-318], [WUMO-328], [WUMO-329]
[WUMO-318]: https://shoekream.atlassian.net/browse/WUMO-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-328]: https://shoekream.atlassian.net/browse/WUMO-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-329]: https://shoekream.atlassian.net/browse/WUMO-329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-279] Member 회원가입 축하 메일 전송 기능 구현

- src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationGetResponse.java
- src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java
- src/main/java/org/prgrms/wumo/global/mapper/LocationMapper.java
- src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java
- src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
후보지 상세 조회시 isEditable 필드 추가
- 후보지 수정 및 삭제 권한을 확인할 수 있도록 프론트엔드 요구사항 반영
- Resolved : [WUMO-352], [WUMO-353]
[WUMO-352]: https://shoekream.atlassian.net/browse/WUMO-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-353]: https://shoekream.atlassian.net/browse/WUMO-353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-351] Location 상세 조회시 isEditable 필드 추가

- src/main/java/org/prgrms/wumo/domain/route/model/Route.java
- src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepositoryImpl.java
- src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
- src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java
- src/test/java/org/prgrms/wumo/domain/like/controller/RouteLikeControllerTest.java
- src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
- src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
- 루트 공개여부 변경 시 루트 이름 변경 가능하도록 반영
- 특이사항은 없습니다.
- Resolved : [WUMO-359], [WUMO-360]
[WUMO-359]: https://shoekream.atlassian.net/browse/WUMO-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-360]: https://shoekream.atlassian.net/browse/WUMO-360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-358] Route 공개여부 변경 기능 요구사항 반영

- src/main/java/org/prgrms/wumo/domain/comment/repository/LocationCommentCustomRepositoryImpl.java
- src/main/java/org/prgrms/wumo/domain/comment/repository/PartyRouteCommentCustomRepositoryImpl.java
댓글 목록 조회시 정렬 기준 변경
기존 오래된 순으로 보이던 댓글을 최신순으로 보이게 변경
프론트엔드 요구사항 반영
- Resolved : [WUMO-366]
[WUMO-366]: https://shoekream.atlassian.net/browse/WUMO-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-365] Comment 정렬 기준 변경

- src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
- src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
- 루트 서비스 레이어 코드 리팩토링
- 현재 코드에서 가독성이나 유지보수면으로 고민해보면 좋을 부분들 이야기해주시면 감사하겠습니다
- Resolved : [WUMO-384], [WUMO-385]
[WUMO-384]: https://shoekream.atlassian.net/browse/WUMO-384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-385]: https://shoekream.atlassian.net/browse/WUMO-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-383]Route 서비스레이어 가독성 위한 코드 리팩토링

- src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java
- src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberPasswordUpdateRequest.java
- src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberUpdateRequest.java
- src/main/java/org/prgrms/wumo/domain/member/model/Member.java
- src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
- src/main/java/org/prgrms/wumo/global/sender/EmailSender.java
- src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java
- src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
- 추후 기능 확장을 고려해 회원 내 정보 수정 기능에서 비밀번호 변경 기능을 분리하였습니다
- 특이사항은 없습니다
- Resolved : [WUMO-393], [WUMO-394], [WUMO-395]
[WUMO-393]: https://shoekream.atlassian.net/browse/WUMO-393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-394]: https://shoekream.atlassian.net/browse/WUMO-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-395]: https://shoekream.atlassian.net/browse/WUMO-395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-392] Member 비밀번호 변경 기능 구현

- src/main/java/org/prgrms/wumo/domain/like/service/RouteLikeService.java
- src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java
- src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
- Party 예외 메세지 ENUM화
- Resolved : [WUMO-391]
[WUMO-391]: https://shoekream.atlassian.net/browse/WUMO-391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-391] Party 예외 메세지 ENUM화

- src/main/java/org/prgrms/wumo/domain/comment/api/LocationCommentController.java
- src/main/java/org/prgrms/wumo/domain/comment/api/ReplyCommentController.java
- src/main/java/org/prgrms/wumo/domain/comment/dto/request/ReplyCommentGetAllRequest.java
- src/main/java/org/prgrms/wumo/domain/comment/dto/response/ReplyCommentGetAllResponse.java
- src/main/java/org/prgrms/wumo/domain/comment/dto/response/ReplyCommentGetResponse.java
- src/main/java/org/prgrms/wumo/domain/comment/model/ReplyComment.java
- src/main/java/org/prgrms/wumo/domain/comment/repository/ReplyCommentCustomRepository.java
- src/main/java/org/prgrms/wumo/domain/comment/repository/ReplyCommentCustomRepositoryImpl.java
- src/main/java/org/prgrms/wumo/domain/comment/repository/ReplyCommentRepository.java
- src/main/java/org/prgrms/wumo/domain/comment/service/ReplyCommentService.java
- src/main/java/org/prgrms/wumo/global/mapper/CommentMapper.java
- src/test/java/org/prgrms/wumo/domain/comment/api/ReplyCommentControllerTest.java
- src/test/java/org/prgrms/wumo/domain/comment/service/ReplyCommentServiceTest.java
대댓글 목록 조회 기능 구현 및 테스트
특이사항 없습니다
- Resolved : [WUMO-380], [WUMO-397], [WUMO-398]
[WUMO-380]: https://shoekream.atlassian.net/browse/WUMO-380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-397]: https://shoekream.atlassian.net/browse/WUMO-397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-398]: https://shoekream.atlassian.net/browse/WUMO-398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-377] ReplyComment 목록 조회 기능 구현

- src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java
- 공통 예외 핸들러 추가
- 없습니다
- Resolved : [WUMO-401]
[WUMO-401]: https://shoekream.atlassian.net/browse/WUMO-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-401] 공통 예외 핸들러 추가

- src/main/java/org/prgrms/wumo/domain/route/dto/request/SortType.java
- src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java
- src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
- src/main/java/org/prgrms/wumo/global/cache/CacheType.java
- src/main/java/org/prgrms/wumo/global/config/RedisCacheConfig.java
- src/main/resources/db/migration/V20__alter_route_add_index.sql
- src/main/resources/db/migration/V21__alter_location_add_index_for_search.sql
- 인덱스 설정
- 정렬 기준별 첫번째 페이지 캐싱 기능 구현(redis cache 사용)
- 인덱스 타는지 여부를 확인했습니다
- 캐싱 후 15분동안 select query가 나가지 않는 것을 확인했습니다
- Resolved : [WUMO-389], [WUMO-390], [WUMO-408]
[WUMO-389]: https://shoekream.atlassian.net/browse/WUMO-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-390]: https://shoekream.atlassian.net/browse/WUMO-390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-408]: https://shoekream.atlassian.net/browse/WUMO-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-388] Route 목록 조회, 검색 기능 성능 개선

- src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetResponse.java
- src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
- src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java
- src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
- 루트 상세 조회 응답 시, 현재 로그인 한 회원이 해당 루트의 좋아요를 눌렀는지 여부 데이터 추가
- 특이사항은 없습니다
- Resolved : [WUMO-414], [WUMO-415]
[WUMO-414]: https://shoekream.atlassian.net/browse/WUMO-414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-415]: https://shoekream.atlassian.net/browse/WUMO-415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-413] Route 상세 조회에 좋아요 기능 반영

- src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java
- 검색어가 입력되지 않은 경우만 캐싱되도록 수정
- 특이사항은 없습니다
- [이슈 정리](https://github.com/prgrms-web-devcourse/Team-5YES-WuMo-BE/issues/150)
- Resolved : [WUMO-424]
[WUMO-424]: https://shoekream.atlassian.net/browse/WUMO-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-423] Route 목록 조회 캐싱 조건 수정

- src/main/java/org/prgrms/wumo/domain/comment/model/Comment.java
- src/main/java/org/prgrms/wumo/domain/comment/service/LocationCommentService.java
- src/main/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentService.java
댓글 도메인 예외 메시지 ENUM 적용
특이사항 없습니다
- Resolved : [WUMO-421], [WUMO-422]
[WUMO-421]: https://shoekream.atlassian.net/browse/WUMO-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-422]: https://shoekream.atlassian.net/browse/WUMO-422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-419] Comment 예외 메시지 ENUM 적용

- src/main/java/org/prgrms/wumo/domain/location/model/Location.java
- src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java
후보지 도메인의 예외 메세지 ENUM 적용
특이사항 없습니다
- Resolved : [WUMO-420]
[WUMO-420]: https://shoekream.atlassian.net/browse/WUMO-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-418] Location 예외 메시지 ENUM 적용

- build.gradle
- src/main/resources/application-log.yml
- src/main/resources/application.yml
- src/main/resources/logback-spring-prod.xml
- 에러 로그 슬랙 연동
- Resolved : [WUMO-431]
[WUMO-431]: https://shoekream.atlassian.net/browse/WUMO-431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WUMO-431] 에러 로그 슬랙 연동

- build.gradle
- src/main/java/org/prgrms/wumo/domain/member/mapper/MemberMapper.java
- src/main/java/org/prgrms/wumo/domain/member/model/Member.java
- src/main/java/org/prgrms/wumo/domain/member/model/Password.java
- src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java
- src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java
- src/main/java/org/prgrms/wumo/global/config/WebConfig.java
- src/main/java/org/prgrms/wumo/global/jwt/CustomAccessDeniedHandler.java
- src/main/java/org/prgrms/wumo/global/jwt/CustomAuthenticationEntryPoint.java
- src/main/java/org/prgrms/wumo/global/jwt/JwtAuthenticationFilter.java
- src/main/java/org/prgrms/wumo/global/jwt/JwtExceptionFilter.java
- src/main/java/org/prgrms/wumo/global/jwt/JwtTokenProvider.java
- src/main/java/org/prgrms/wumo/global/oauth/OauthAuthenticationSuccessHandler.java
- src/main/java/org/prgrms/wumo/global/oauth/dto/OauthLoginResponse.java
- src/main/java/org/prgrms/wumo/global/oauth/model/Oauth2Attributes.java
- src/main/java/org/prgrms/wumo/global/oauth/model/SocialOauthType.java
- src/main/java/org/prgrms/wumo/global/oauth/service/CustomOauthService.java
- src/main/java/org/prgrms/wumo/global/sender/EmailSender.java
- src/main/resources/application-security.yml
- src/main/resources/db/migration/V23__alter_member_change_password_null.sql
- src/test/java/org/prgrms/wumo/domain/image/api/ImageControllerTest.java
- src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
- src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
- src/test/resources/application-test.yml
- google social login 기능 구현
- oauth를 통해 가입한 회원 구분을 위해 password null을 허용하였습니다
- 순환참조로 인해 시큐리티 관련 파일들을 빈주입에서 생성자 주입으로 변경하였습니다
<br/>
- Oauth2Attributes : provider로부터 오는 다른 JSON 형식들을 관리하기 위한 클래스
- CustomOauthService : provider로부터 받은 회원 정보를 가공하는 클래스
- OauthAuthenticationSuccessHandler : OAuth 로그인 성공 시 호출되는 handler
- Resolved : [WUMO-428], [WUMO-430], [WUMO-435], [WUMO-436]
[WUMO-428]: https://shoekream.atlassian.net/browse/WUMO-428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-430]: https://shoekream.atlassian.net/browse/WUMO-430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-435]: https://shoekream.atlassian.net/browse/WUMO-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
> [WUMO-339] OAuth(google) 로그인 기능 구현
