prgrms-web-devcourse/Team-5YES-WuMo-BE

src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java, src/main/java/org/prgrms/wumo/domain/member/repository/MemberRepository.java, src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java, src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java, src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
- 회원 닉네임 중복체크 기능 구현 및 테스트 코드
- Resolved : [WUMO-136], [WUMO-137]
[WUMO-136]: https://shoekream.atlassian.net/browse/WUMO-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-137]: https://shoekream.atlassian.net/browse/WUMO-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-28] Member 닉네임 중복체크 기능 구현

src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java, src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java, src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberRepository.java, src/main/java/org/prgrms/wumo/domain/party/repository/PartyRepository.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java, src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java, src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java, src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java, src/test/java/org/prgrms/wumo/domain/party/model/PartyTest.java, src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
- 모임 등록 기능 구현
- 등록 로직에 "파티 등록", "파티장 조회 및 등록"이 포함되어 있습니다.
- MemberRepository는 어느 서비스에서라도 쓰는 게 좋지 않을까요?
- Resolved : [WUMO-145], [WUMO-147]
[WUMO-145]: https://shoekream.atlassian.net/browse/WUMO-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-147]: https://shoekream.atlassian.net/browse/WUMO-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-34] Party 등록 기능 구현

src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java, src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetDetailResponse.java, src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberRepository.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java, src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java, src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java, src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
- 사용자 기준 모임 목록 조회 기능 구현
- QueryDSL을 통한 커서 페이지네이션은 기능 개발이 끝난 후에 작업 예정입니다.
- Resolved : [WUMO-154], [WUMO-155]
[WUMO-154]: https://shoekream.atlassian.net/browse/WUMO-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-155]: https://shoekream.atlassian.net/browse/WUMO-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-38] Party 목록 조회 기능 구현

src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java, src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java, src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
- 모임(Party) 상세 조회 기능 구현 및 테스트
- 모임 CRUD가 모두 구현된 뒤에 Authencation에서 memberId를 가져오는 방법으로 변경 예정입니다.
- Resolved : [WUMO-156], [WUMO-157]
[WUMO-156]: https://shoekream.atlassian.net/browse/WUMO-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-157]: https://shoekream.atlassian.net/browse/WUMO-157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-39] Party 상세 조회 기능 구현

src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java, src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java, src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberRepository.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java, src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java, src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
- 모임(Party) 삭제 기능 구현 및 테스트
- 지난번 PR 중점 사항과 마찬가지로 로그인 된 사용자 검증은 전체 기능 개발 완료 후 적용 예정입니다.
- Resolved : [WUMO-161], [WUMO-162]
[WUMO-161]: https://shoekream.atlassian.net/browse/WUMO-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-162]: https://shoekream.atlassian.net/browse/WUMO-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-35] Party 삭제 기능 구현

src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java, src/main/java/org/prgrms/wumo/domain/location/dto/request/LocationGetAllRequest.java, src/main/java/org/prgrms/wumo/domain/location/dto/response/LocationGetAllResponse.java, src/main/java/org/prgrms/wumo/domain/location/repository/LocationRepository.java, src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java, src/main/java/org/prgrms/wumo/global/mapper/LocationMapper.java, src/test/java/org/prgrms/wumo/domain/location/LocationTestUtils.java, src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java, src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
Location 목록 조회 기능 구현
- 현재는 단순 조회기능만 구현했습니다. 추후 queryDSL을 이용한 커서 기반 페이징으로 고칠 생각입니다!
- 일단 목록 조회에서 페이지 사이즈 만큼 가져오려고 시도 했는데 JPQL 에서는 limit을 사용 못해서 페이지 사이즈 5 고정으로 가정하고 서비스 코드 작성했습니다!
- Resolved : WUMO-46
=> [WUMO-46] Location 목록 조회 기능 구현

src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java, src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteRegisterRequest.java, src/main/java/org/prgrms/wumo/domain/route/model/Route.java, src/main/java/org/prgrms/wumo/domain/route/repository/RouteRepository.java, src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java, src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java, src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java, src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java, src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java, src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
- 후보지를 루트에 등록하는 기능 구현 및 테스트
- 객체의 연관관계들로 인해 테스트 코드가 많이 깁니다
조금 더 줄일 수 있는 방법이 있을까요?
- 현재 로그인한 사용자가 해당 모임멤버인지 검증 후 
맞다면 루트에 후보지를 등록할 수 있도록 로직을 구현하였습니다
제가 놓친 부분이 없는지, 코드를 조금 더 깔끔하게 짤 수 있을지 등등 
루트 등록 서비스 코드를 꼼꼼하게 매운맛으로 봐주시면 감사하겠습니다!
- Resolved : [WUMO-179], [WUMO-180]
[WUMO-179]: https://shoekream.atlassian.net/browse/WUMO-179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-180]: https://shoekream.atlassian.net/browse/WUMO-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-52] Route 등록 기능 구현

src/main/java/org/prgrms/wumo/domain/party/api/PartyController.java, src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java, src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepository.java, src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepositoryImpl.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java, src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java, src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
- Party(모임) 서비스 코드 전역에 등록, 조회, 수정, 삭제에 JwtUtil를 활용한 Access 제어 추가
- 특이사항 없음
- Resolved : [WUMO-182], [WUMO-183]
[WUMO-182]: https://shoekream.atlassian.net/browse/WUMO-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-183]: https://shoekream.atlassian.net/browse/WUMO-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-181] Party 기능 전역에 로그인 기능 추가 구현

src/main/java/org/prgrms/wumo/domain/party/api/PartyMemberController.java, src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java, src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyUpdateRequest.java, src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetResponse.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java, src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java, src/main/java/org/prgrms/wumo/global/exception/custom/PartyNotEmptyException.java, src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java, src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java, src/test/java/org/prgrms/wumo/domain/party/api/PartyMemberControllerTest.java, src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java, src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
- 모임 구성원(PartyMember) 삭제(탈퇴, 추방) 기능 구현 및 테스트
- 엔드포인트와 메서드를 분리했지만 파티장이 자신을 추방하는 경우도 가능하게 구현했습니다.
- deletePartyMember(Party, Member) 에서 대상이 되는 Member가 자신인 경우
- deletePartyMember(Party)인 탈퇴 처리 로직을 호출합니다.
- Resolved : [WUMO-198], [WUMO-199]
[WUMO-198]: https://shoekream.atlassian.net/browse/WUMO-198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-199]: https://shoekream.atlassian.net/browse/WUMO-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-40] PartyMember 삭제 기능 구현

src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java, src/main/java/org/prgrms/wumo/domain/location/model/Location.java, src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java, src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java, src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java, src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java, src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java, src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
- 루트에서 후보지 삭제 기능 구현 및 테스트
- 후보지의 루트 상태를 삭제하기 위해 Location 객체에서 null로 변환후 dirty checking 하는 방식으로 구현하였습니다
null을 주입하는 방법이 옳은가 의문이 들기도 합니다
더 좋은 방법이 있을까 같이 고민해주시면 감사하겠습니다
- Resolved : [WUMO-208], [WUMO-209]
[WUMO-208]: https://shoekream.atlassian.net/browse/WUMO-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-209]: https://shoekream.atlassian.net/browse/WUMO-209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-53] Route에서 Location 삭제 기능 구현

src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteGetAllRequest.java, src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteRegisterRequest.java, src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteStatusUpdateRequest.java, src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java, src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteLocationResponse.java, src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteLocationSimpleResponse.java, src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java, src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java, src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
- 루트 API 명세서에 요구사항 변경 반영 및 단어 통일
프론트와 상의 후 
- 루트를 공개로 변경 시 사용할 루트의 이름을 회원에게 받기로 하였습니다(default 값은 루트가 속한 모임의 이름)
- 공개된 루트 목록에서 루트의 썸네일 이미지는 모임의 썸네일 이미지를 응답하기로 했습니다
- Resolved : [WUMO-211], [WUMO-212]
[WUMO-211]: https://shoekream.atlassian.net/browse/WUMO-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-212]: https://shoekream.atlassian.net/browse/WUMO-212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-210] Route API 명세서에 요구사항 변경 반영

src/main/java/org/prgrms/wumo/domain/comment/api/RouteCommentController.java, src/main/java/org/prgrms/wumo/domain/comment/dto/request/PartyRouteCommentRegisterRequest.java, src/main/java/org/prgrms/wumo/domain/comment/model/PartyRouteComment.java, src/main/java/org/prgrms/wumo/domain/comment/repository/PartyRouteCommentRepository.java, src/main/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentService.java, src/main/java/org/prgrms/wumo/global/mapper/CommentMapper.java, src/main/resources/db/migration/V6__alter_party_route_comment_add_location_id.sql, src/test/java/org/prgrms/wumo/domain/comment/api/PartyRouteCommentControllerTest.java, src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
PartyRouteComment 등록 기능 구현 및 테스트
이전에 PartyRouteComment 는 Location Id 를 필드로 들고 있지 않아도 연관관계를 이용해서 작성하려 했으나, 
있어야겠다고 판단, 칼럼을 추가했습니다.
명세서 등의 용어 통일 은 추후 다른 작업에서 진행할 예정입니다
- Resolved : WUMO-91
=> [WUMO-91] PartyRouteComment 등록 기능 구현

src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java, src/main/java/org/prgrms/wumo/domain/member/dto/request/MemberReissueRequest.java, src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java, src/main/java/org/prgrms/wumo/global/exception/GlobalExceptionHandler.java, src/main/java/org/prgrms/wumo/global/exception/custom/InvalidRefreshTokenException.java, src/main/java/org/prgrms/wumo/global/jwt/JwtTokenProvider.java
- token 재발급 기능 구현
- access token 만료 시 refresh token 검증 후 token 재발급
- token 저장위치를 Redis로 변경 예정입니다
- Resolved : [WUMO-239], [WUMO-240]
[WUMO-239]: https://shoekream.atlassian.net/browse/WUMO-239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-240]: https://shoekream.atlassian.net/browse/WUMO-240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-144] Token 재발급 기능 구현

src/main/java/org/prgrms/wumo/domain/like/controller/RouteLikeController.java, src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeRepository.java, src/main/java/org/prgrms/wumo/domain/like/service/RouteLikeService.java, src/main/java/org/prgrms/wumo/global/mapper/LikeMapper.java, src/test/java/org/prgrms/wumo/domain/like/controller/RouteLikeControllerTest.java, src/test/java/org/prgrms/wumo/domain/like/service/RouteLikeServiceTest.java
- RouteLike 등록 기능 구현 및 테스트
- 좋아요 등록 과정에서 다음과 같은 검증이 이루어집니다.
- 존재하는 루트 및 사용자 인가
- 이미 해당 루트에 좋아요를 누른 사용자 인가
- Resolved : [WUMO-251], [WUMO-252]
[WUMO-251]: https://shoekream.atlassian.net/browse/WUMO-251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-252]: https://shoekream.atlassian.net/browse/WUMO-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-58] RouteLike 등록 기능 구현

src/main/java/org/prgrms/wumo/domain/like/controller/RouteLikeController.java, src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeRepository.java, src/main/java/org/prgrms/wumo/domain/like/service/RouteLikeService.java, src/test/java/org/prgrms/wumo/domain/like/controller/RouteLikeControllerTest.java, src/test/java/org/prgrms/wumo/domain/like/service/RouteLikeServiceTest.java
- RouteLike 삭제 기능 구현 및 테스트
- 엔드포인트를 등록과 동일하게 변경했습니다.
- Resolved : [WUMO-253], [WUMO-254]
[WUMO-253]: https://shoekream.atlassian.net/browse/WUMO-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-254]: https://shoekream.atlassian.net/browse/WUMO-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-63] RouteLike 삭제 기능 구현

src/main/java/org/prgrms/wumo/domain/comment/api/LocationCommentController.java, src/main/java/org/prgrms/wumo/domain/comment/service/LocationCommentService.java, src/test/java/org/prgrms/wumo/domain/comment/api/LocationCommentControllerTest.java, src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java
후보지 댓글 삭제 기능 구현 및 테스트
후보지 댓글 삭제 기능입니다.
추후 리팩토링이 필요한 부분이 존재합니다
- getMemerEntity 메소드를 getPartyMemberEntity 의 member 필드를 가져오는 방식으로 대체
- Resolved : WUMO-255, WUMO-256
=> [WUMO-85] LocationComment 삭제 기능 구현

src/main/java/org/prgrms/wumo/domain/comment/api/RouteCommentController.java, src/main/java/org/prgrms/wumo/domain/comment/dto/request/PartyRouteCommentUpdateRequest.java, src/main/java/org/prgrms/wumo/domain/comment/dto/response/PartyRouteCommentUpdateResponse.java, src/main/java/org/prgrms/wumo/domain/comment/model/PartyRouteComment.java, src/main/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentService.java, src/main/java/org/prgrms/wumo/global/mapper/CommentMapper.java, src/test/java/org/prgrms/wumo/domain/comment/api/PartyRouteCommentControllerTest.java, src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
모임 내 루트 댓글 수정 기능 구현 및 테스트
모임 내 루트 수정 기능입니다.
추후 리팩토링을 진행할 부분이 존재하는 코드입니다
리팩토링은 삭제 기능까지 구현 완료 후 바로 진행 예정입니다.
- isEdited 칼럼 삭제
- 댓글 작성자 확인 메소드를 엔티티 내부로 이동
- getMemberEntity 메소드를 partyMember 엔티티를 사용하는 방식으로 변경
- Resolved : WUMO-259, WUMO-260
=> [WUMO-83] PartyRouteComment 수정 기능 구현

src/main/java/org/prgrms/wumo/domain/comment/api/RouteCommentController.java, src/main/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentService.java, src/test/java/org/prgrms/wumo/domain/comment/api/PartyRouteCommentControllerTest.java, src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
모임 내 루트 댓글 삭제 기능 구현 및 테스트
모임 내 루트 삭제 기능입니다.
추후 리팩토링을 진행할 부분이 존재하는 코드입니다
리팩토링은 본 기능이 반영되면 시작할 예정입니다!
- isEdited 칼럼 삭제
- 댓글 작성자 확인 메소드를 엔티티 내부로 이동
- getMemberEntity 메소드를 partyMember 엔티티를 사용하는 방식으로 변경
- Resolved : WUMO-264, WUMO-265
=> [WUMO-86] PartyRouteComment 삭제 기능 구현

src/main/java/org/prgrms/wumo/domain/comment/api/LocationCommentController.java, src/main/java/org/prgrms/wumo/domain/comment/api/RouteCommentController.java, src/main/java/org/prgrms/wumo/domain/comment/dto/request/LocationCommentGetAllRequest.java, src/main/java/org/prgrms/wumo/domain/comment/dto/request/LocationCommentRegisterRequest.java, src/main/java/org/prgrms/wumo/domain/comment/dto/request/LocationCommentUpdateRequest.java, src/main/java/org/prgrms/wumo/domain/comment/dto/request/PartyRouteCommentGetAllRequest.java, src/main/java/org/prgrms/wumo/domain/comment/dto/request/PartyRouteCommentRegisterRequest.java, src/main/java/org/prgrms/wumo/domain/comment/dto/request/PartyRouteCommentUpdateRequest.java, src/main/java/org/prgrms/wumo/domain/comment/dto/response/LocationCommentGetAllResponse.java, src/main/java/org/prgrms/wumo/domain/comment/dto/response/LocationCommentGetResponse.java, src/main/java/org/prgrms/wumo/domain/comment/dto/response/LocationCommentRegisterResponse.java, src/main/java/org/prgrms/wumo/domain/comment/dto/response/LocationCommentUpdateResponse.java, src/main/java/org/prgrms/wumo/domain/comment/dto/response/PartyRouteCommentGetAllResponse.java, src/main/java/org/prgrms/wumo/domain/comment/dto/response/PartyRouteCommentGetResponse.java, src/main/java/org/prgrms/wumo/domain/comment/dto/response/PartyRouteCommentRegisterResponse.java, src/main/java/org/prgrms/wumo/domain/comment/dto/response/PartyRouteCommentUpdateResponse.java
댓글 API 명세서 정리
- Swagger required -> requiredMode 로 변경
- 용어 통일
- 아이디, id -> 식별자 정리
- 후보 장소 -> 후보지로 통일
- 비어 있는 에러 메세지 채우기
- Resolved : WUMO-267, WUMO-268
=> [WUMO-266] Comment API 명세서 보완 및 용어 정리

src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyGetRequest.java, src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyType.java, src/main/java/org/prgrms/wumo/domain/party/model/Party.java, src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepository.java, src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepositoryImpl.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java, src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java, src/test/java/org/prgrms/wumo/domain/party/model/PartyTest.java, src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
- Party 조회 기준 기능 구현 및 테스트
- 조회 기준은 요구사항에 맞춰 3가지 ENUM으로 정의했습니다.
- 결과값의 정렬 기준은 최신순이고 나중에 등록한 모임 기준으로 상위에 조회됩니다.
- Resolved : [WUMO-276], [WUMO-277]
[WUMO-276]: https://shoekream.atlassian.net/browse/WUMO-276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-277]: https://shoekream.atlassian.net/browse/WUMO-277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-274] Party 조회 기준 기능 구현

src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyGetRequest.java, src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyUpdateRequest.java, src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetAllResponse.java, src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyGetResponse.java, src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyMemberGetAllResponse.java, src/main/java/org/prgrms/wumo/domain/party/model/Party.java, src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberRepository.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java, src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java, src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java, src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
- Party 조회시 구성원 및 전체 멤버 수 포함 기능 구현 및 테스트
- 프론트엔드 요청에 따라 PartyMemberService의 일부 기능이 PartyService에 들어갔습니다.
- Resolved : [WUMO-283], [WUMO-284]
[WUMO-283]: https://shoekream.atlassian.net/browse/WUMO-283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-284]: https://shoekream.atlassian.net/browse/WUMO-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-273] Party 조회시 구성원 및 전체 멤버 수 포함 기능 구현

src/main/java/org/prgrms/wumo/WumoFinalApplication.java, src/main/java/org/prgrms/wumo/batch/like/RouteLikeBatchComponent.java, src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeCustomRepository.java, src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeCustomRepositoryImpl.java, src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeRepository.java, src/main/java/org/prgrms/wumo/global/config/BatchConfig.java
- RouteLike 집계 스케줄링 (Batch) 기능 구현
- 테스트는 로컬에서 완료했습니다.
- 배치 주기나 크기는 추후 성능 테스트 후 조절 예정입니다.
- Resolved : [WUMO-66]
[WUMO-66]: https://shoekream.atlassian.net/browse/WUMO-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-66] RouteLike 집계 스케줄링 (Batch) 기능 구현

src/main/java/org/prgrms/wumo/domain/route/dto/request/SortType.java, src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java, src/main/java/org/prgrms/wumo/domain/route/model/Route.java, src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepositoryImpl.java, src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java, src/main/java/org/prgrms/wumo/global/config/SecurityConfig.java, src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java, src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
- 좋아요 기능이 추가됨에 따라 루트 목록 조회 응답 시,
현재 로그인 하고 있는 회원이 해당 루트의 좋아요를 눌렀는지 여부를 같이 보내도록 추가하였습니다
- 현재 RouteService에서 좋아요 눌렀는지 여부(isLiking)의 필드를 하나의 루트마다 for문 안에서 추가해주고 있습니다
추후 join으로 한번에 가져올 수 있을지 고민해 볼 예정입니다
더 좋은 방법이 있을지 같이 고민해주시면 감사하겠습니다
- Resolved : [WUMO-298], [WUMO-299]
[WUMO-298]: https://shoekream.atlassian.net/browse/WUMO-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-299]: https://shoekream.atlassian.net/browse/WUMO-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-288] Route 목록 조회 응답 시 좋아요 여부 추가

src/main/java/org/prgrms/wumo/domain/comment/dto/request/LocationCommentRegisterRequest.java, src/main/java/org/prgrms/wumo/domain/comment/dto/request/PartyRouteCommentRegisterRequest.java, src/main/java/org/prgrms/wumo/domain/comment/model/Comment.java, src/main/java/org/prgrms/wumo/domain/comment/service/LocationCommentService.java, src/main/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentService.java, src/main/java/org/prgrms/wumo/global/mapper/CommentMapper.java, src/test/java/org/prgrms/wumo/domain/comment/api/LocationCommentControllerTest.java, src/test/java/org/prgrms/wumo/domain/comment/api/PartyRouteCommentControllerTest.java, src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java, src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
댓글에서 사용자를 검증 방식 리팩토링
최대한 적은 Repository를 주입받고자 리팩토링을 진행했습니다
- 기존 getMemberEntity 로 Member 주입 -> partyMember.member 로 대체
- 댓글 작성자와 현재 접속중인 사람을 확인하는 메소드를 comment entity 내부로 위치 이동
- 기존 수정 및 삭제시 댓글 작성자 확인 + 모임 내 멤버 검증을 진행하는 메소드가 분리되어있던 것을 하나의 메소드로 묶음
추가로 댓글 등록 요청 dto의 필드에서 
- memberId 제거,
- roueId -> partyId 로 변경
의 작업을 진행했습니다.
- Resolved : [이슈번호], [이슈번호]
=> [WUMO-297] Comment 검증 로직 리팩토링

src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java, src/main/java/org/prgrms/wumo/domain/route/model/Route.java, src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepository.java, src/main/java/org/prgrms/wumo/domain/route/repository/RouteCustomRepositoryImpl.java, src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java, src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java, src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java, src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
루트 상세 조회 기능 요구사항 반영
- 루트 식별자로 조회가 아닌(프론트에서 루트 식별자를 알 방법이 없음)
루트가 속한 모임의 식별자로 루트의 상세 조회를 요청하게 됩니다
- 응답 시에는 루트 안의 후보지들의 정렬 기준을 방문일로 구현하였습니다
- 현재 JPA를 활용해 루트 안의 후보지들을 lazy loading으로 가져오기 때문에 application단에서 방문일 기준으로 정렬하는 과정도 가능합니다
- 지금 구현한 방법(order by 사용)과 비교했을 때 현재의 데이터 크기로는 큰 차이가 없었으나 여건이 된다면 추후 더 큰 데이터로도 비교해볼 예정입니다
- Resolved : [WUMO-310], [WUMO-311], [WUMO-312]
[WUMO-310]: https://shoekream.atlassian.net/browse/WUMO-310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-311]: https://shoekream.atlassian.net/browse/WUMO-311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-312]: https://shoekream.atlassian.net/browse/WUMO-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …
=> [WUMO-287] Route 상세 조회 기능 요구사항 반영

src/main/java/org/prgrms/wumo/domain/location/api/LocationController.java, src/main/java/org/prgrms/wumo/domain/location/model/Location.java, src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java, src/main/java/org/prgrms/wumo/global/mapper/LocationMapper.java, src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java, src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
후보지 실제 사용 금액 갱신 기능 구현 및 테스트
후보지 실제 사용 금액 갱신 기능입니다.
현재는 모임 내 인원이면 모두 갱신이 가능한데, 
곧 후보지를 올린 사람 및 모임장만 갱신할 수 있도록 로직 개선 예정입니다
- Resolved : WUMO-308, WUMO-309
=> [WUMO-307] Location 실제 사용 금액 갱신 기능 구현

src/main/java/org/prgrms/wumo/domain/image/repository/ImageRepository.java, src/main/java/org/prgrms/wumo/domain/image/service/ImageService.java, src/test/java/org/prgrms/wumo/domain/image/api/ImageControllerTest.java
- Image 서비스 책임 변경 (Service -> Repository)
- 계층형 아키텍처에 맞게 구조를 변경했습니다.
- 추후 이미지를 사용하는 각 서비스에서 도메인 엔티티 삭제시 이미지 삭제 요청은 Repository로 전달합니다.
- Resolved : [WUMO-316]
[WUMO-316]: https://shoekream.atlassian.net/browse/WUMO-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-316] Image 서비스 책임 변경

src/main/java/org/prgrms/wumo/domain/location/model/Location.java, src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java, src/main/java/org/prgrms/wumo/global/mapper/LocationMapper.java, src/main/resources/db/migration/V14__alter_location_add_member_id.sql, src/test/java/org/prgrms/wumo/domain/comment/api/LocationCommentControllerTest.java, src/test/java/org/prgrms/wumo/domain/comment/api/PartyRouteCommentControllerTest.java, src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java, src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java, src/test/java/org/prgrms/wumo/domain/like/controller/RouteLikeControllerTest.java, src/test/java/org/prgrms/wumo/domain/location/LocationTestUtils.java, src/test/java/org/prgrms/wumo/domain/location/api/LocationControllerTest.java, src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java, src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java, src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
후보지 수정 및 삭제 권한 변경
- 후보지 권한 확인을 위한 스키마 변경 (location 에 member_id 추가)
- 이로 인한 Location 을 사용하는 테스트 코드에서 필드 추가
- 후보지 수정 및 삭제 권한
- 기존 : 모임내 모든 인원 -> 변경 후 : 후보지 등록인 및 모임장
- 변경된 권한 테스트
- Resolved : WUMO-324, WUMO-325, WUMO-326, WUMO-327
=> [WUMO-323] Location 수정 및 삭제 권한 변경

src/main/java/org/prgrms/wumo/domain/image/repository/ImageRepository.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java, src/test/java/org/prgrms/wumo/domain/party/api/PartyControllerTest.java, src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java, src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
- Party 삭제 및 탈퇴 기능 리팩토링
- Image 삭제시 경로에 문제가 있을 경우 log만 남기는 정도로 변경했습니다.
- Resolved : [WUMO-330]
[WUMO-330]: https://shoekream.atlassian.net/browse/WUMO-330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-330] Party 삭제 및 탈퇴 기능 리팩토링

src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepository.java, src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberCustomRepositoryImpl.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java, src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
- 모임 조회 N*2 쿼리 성능 개선
- 기존 10개 목록 조회 기준 20개 이상의 쿼리가 발생했고 3번의 쿼리만 실행하도록 개선했습니다.
- 모임 목록의 각 정보를 먼저 탐색
- 각 목록의 총 구성원 수를 탐색
- 각 목록의 리더를 탐색
- 구성원 미리보기 N명 가져오는 쿼리 복잡도가 높아 파티장만 가져오도록 정책을 변경했습니다.
- 추후 서비스 개선사항에 포함될 것 같습니다.
- Resolved : [WUMO-321]
[WUMO-321]: https://shoekream.atlassian.net/browse/WUMO-321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-321] 모임 조회 N*2 쿼리 성능 개선

src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java, src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java, src/main/java/org/prgrms/wumo/global/config/WebConfig.java, src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java, src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
- 내 정보 조회 기능에서 client에서 memberId를 받아오지 않고  
서버쪽에서 현재 로그인한 유저의 정보를 보내주는 것으로 변경했습니다  
- 특이사항은 없습니다
- Resolved : [WUMO-336], [WUMO-337]
[WUMO-336]: https://shoekream.atlassian.net/browse/WUMO-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-337]: https://shoekream.atlassian.net/browse/WUMO-337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-335] Member 내 정보 조회 기능 리팩토링

src/main/java/org/prgrms/wumo/domain/party/api/PartyMemberController.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java, src/test/java/org/prgrms/wumo/domain/party/api/PartyMemberControllerTest.java, src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java
- 모임 내 회원의 상세 정보 조회 기능 구현 및 테스트
- 모임 내 회원의 역할 변경 전 해당 회원의 모임 내 정보를 조회해야하는 요구사항에 따른 기능 추가
- Resolved : [WUMO-333], [WUMO-334]
[WUMO-333]: https://shoekream.atlassian.net/browse/WUMO-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-334]: https://shoekream.atlassian.net/browse/WUMO-334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-332] PartyMember 상세 조회 기능 구현

src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeCustomRepository.java, src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeCustomRepositoryImpl.java, src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberRepository.java, src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java, src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java, src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java, src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
- Route 관심 루트 목록 조회 기능 구현 및 테스트
- Pair를 사용해서 RouteLike 기준으로 Cursor ID를 뱉도록 구현했습니다.
- Resolved : [WUMO-347], [WUMO-348]
[WUMO-347]: https://shoekream.atlassian.net/browse/WUMO-347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-348]: https://shoekream.atlassian.net/browse/WUMO-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-322] Route 관심 루트 목록 조회 기능 구현

src/main/java/org/prgrms/wumo/domain/party/dto/response/PartyMemberGetResponse.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java, src/main/java/org/prgrms/wumo/global/mapper/PartyMapper.java, src/test/java/org/prgrms/wumo/domain/party/api/PartyMemberControllerTest.java, src/test/java/org/prgrms/wumo/domain/party/service/PartyMemberServiceTest.java
- PartyMember 조회 시 isLeader 필드 추가
- 자신의 권한을 확인할 수 있도록 프론트엔드 요구사항 반영
- Resolved : [WUMO-349]
[WUMO-349]: https://shoekream.atlassian.net/browse/WUMO-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-349] PartyMember 조회 시 isLeader 필드 추가

src/main/java/org/prgrms/wumo/domain/comment/dto/response/LocationCommentGetResponse.java, src/main/java/org/prgrms/wumo/domain/comment/dto/response/PartyRouteCommentGetResponse.java, src/main/java/org/prgrms/wumo/domain/comment/service/LocationCommentService.java, src/main/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentService.java, src/main/java/org/prgrms/wumo/global/mapper/CommentMapper.java, src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java, src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java
후보지 댓글, 모임 내 루트 댓글 상세 조회 dto 에 isEditable 필드 추가
댓글을 수정 및 삭제할 수 있는지 확인할 수 있는 필드 isEditable 필드가 추가되었습니다.
후보지와 달리 댓글은 작성자만 수정, 삭제가 가능합니다
- Resolved : [WUMO-355], [WUMO-356], [WUMO-357]
[WUMO-355]: https://shoekream.atlassian.net/browse/WUMO-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-356]: https://shoekream.atlassian.net/browse/WUMO-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-357]: https://shoekream.atlassian.net/browse/WUMO-357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-354] Comment 상세 조회 응답 DTO isEditable 필드 추가

src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java, src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
- Party 상세조회 권한 검증 기능 추가 구현 및 테스트
- 특이사항 없음
- Resolved : [WUMO-39], [WUMO-371], [WUMO-371]
[WUMO-39]: https://shoekream.atlassian.net/browse/WUMO-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-371]: https://shoekream.atlassian.net/browse/WUMO-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-371]: https://shoekream.atlassian.net/browse/WUMO-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-370] Party 상세조회 권한 검증 기능 추가 구현

src/main/java/org/prgrms/wumo/domain/member/api/MemberController.java, src/main/java/org/prgrms/wumo/domain/member/repository/MemberCustomRepository.java, src/main/java/org/prgrms/wumo/domain/member/repository/MemberCustomRepositoryImpl.java, src/main/java/org/prgrms/wumo/domain/member/repository/MemberRepository.java, src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java, src/test/java/org/prgrms/wumo/domain/member/api/MemberControllerTest.java, src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
- 이메일 중복체크 쿼리문 수정
- 이메일로 회원찾기 쿼리문 수정
- Member의 Email을 Embedded type으로 관리하고 있어    
메소드쿼리 사용 시, 불필요한 Email 객체를 생성해야 하는 경우가 있어 리팩토링 하였습니다
- jpql은 select exists 문법 미지원, where 절에서 사용 시에는 count 쿼리 사용함으로 인한 성능상 이슈가 발생해 querydsl을 사용하였습니다
- 중복 체크 시 중복이 없다면 응답하는 http status code를 204(no content)에서 200(ok)로 변경하였습니다 (204는 있던 리소스가 삭제 후 없다는 의미이기 때문에 적절하지 못하다고 판단함)
- Resolved : [WUMO-368], [WUMO-369]
[WUMO-368]: https://shoekream.atlassian.net/browse/WUMO-368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-369]: https://shoekream.atlassian.net/browse/WUMO-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-367] Member 이메일 관련 기능 쿼리 튜닝

src/main/java/org/prgrms/wumo/domain/comment/api/LocationCommentController.java, src/main/java/org/prgrms/wumo/domain/comment/dto/request/ReplyCommentRegisterRequest.java, src/main/java/org/prgrms/wumo/domain/comment/dto/response/ReplyCommentRegisterResponse.java, src/main/java/org/prgrms/wumo/domain/comment/model/ReplyComment.java, src/main/java/org/prgrms/wumo/domain/comment/repository/ReplyCommentRepository.java, src/main/java/org/prgrms/wumo/domain/comment/service/ReplyCommentService.java, src/main/java/org/prgrms/wumo/global/mapper/CommentMapper.java, src/main/resources/db/migration/V19__create_table_if_not_exists_reply_comment.sql, src/test/java/org/prgrms/wumo/domain/comment/api/LocationCommentControllerTest.java, src/test/java/org/prgrms/wumo/domain/comment/service/ReplyCommentServiceTest.java
대댓글 엔티티 추가 및 등록 기능 구현, 테스트
대댓글 엔티티가 추가되었습니다!!
- 추후 nosql을 도입하더라도 정합성 보장을 위해 DB 중복 저장을 위해 대댓글을 RDB로 구현했습니다
- 현재 대댓글은 후보지 댓글에서만 작성 가능하므로 location controller 에 엔드포인트를 추가하는 방식으로 구현했습니다
- Resolved : [WUMO-344], [[WUMO-345], [WUMO-346]
[WUMO-344]: https://shoekream.atlassian.net/browse/WUMO-344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-345]: https://shoekream.atlassian.net/browse/WUMO-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-346]: https://shoekream.atlassian.net/browse/WUMO-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-94] ReplyComment 엔티티 추가 및  등록 기능 구현

src/main/java/org/prgrms/wumo/domain/location/model/Location.java, src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java, src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
후보지 실제 사용 금액 수정 권한 변경
후보지에서 실사용한 금액의 수정 권한을 변경함
- 변경 전 : 모임장 및 후보지 등록인(후보지 수정 삭제 권한과 동일)
- 변경 후 : 모임내 모든 인원
- Resolved : [WUMO-375], [WUMO-376]
[WUMO-375]: https://shoekream.atlassian.net/browse/WUMO-375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-376]: https://shoekream.atlassian.net/browse/WUMO-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-374] Location 실제 사용 금액 수정 권한 변경

src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java, src/main/java/org/prgrms/wumo/global/exception/ExceptionMessage.java, src/test/java/org/prgrms/wumo/domain/member/service/MemberServiceTest.java
- 공통 예외메시지 Enum으로 관리
- 모든 도메인에서 공통적으로 사용하는 예외와 관련된 메시지들만 모아두었습니다
- 빠진 예외메시지가 있다면 말씀해주세요
- Resolved : [WUMO-381], [WUMO-382]
[WUMO-381]: https://shoekream.atlassian.net/browse/WUMO-381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-382]: https://shoekream.atlassian.net/browse/WUMO-382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-379] 공통 예외메시지 Enum으로 관리

src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyMemberRegisterRequest.java, src/main/java/org/prgrms/wumo/domain/party/dto/request/PartyRegisterRequest.java, src/main/java/org/prgrms/wumo/domain/party/model/Party.java
- PartyMember 등록시 역할 Nullable 허용 
- 프론트엔드 요구사항 중 "초대 코드를 통한 모임 참여 시 역할은 지정하지 않고 나중에 설정"에 대한 반영 사항입니다.
- [WUMO-41] 에 대한 요구사항 변경입니다.
- Resolved : [WUMO-41], [WUMO-387]
[WUMO-41]: https://shoekream.atlassian.net/browse/WUMO-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-41]: https://shoekream.atlassian.net/browse/WUMO-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-387]: https://shoekream.atlassian.net/browse/WUMO-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-387] PartyMember 등록시 역할 Nullable 허용

src/main/java/org/prgrms/wumo/batch/like/RouteLikeBatchComponent.java, src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeCustomRepository.java, src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeCustomRepositoryImpl.java
- RouteLike 집계(Batch) COUNT 0 이슈 수정
- COUNT시 좋아요가 없는 Route ID는 집계되지 않는 문제
- 예를 들어 좋아요가 1개이던 루트의 좋아요가 취소되면 COUNT 결과에 포함되지 않음
- 따라서 N -> 0 으로 좋아요 개수가 변경된 것들에 대해 미갱신 문제가 발생
- Resolved : [WUMO-66], [WUMO-399]
[WUMO-66]: https://shoekream.atlassian.net/browse/WUMO-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-399]: https://shoekream.atlassian.net/browse/WUMO-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-399] RouteLike 집계(Batch) COUNT 0 이슈 수정

src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java
- Party 수정시 종료일 +1 이슈 해결
- LocalTime.MAX로 들어가 DB에 23:59:59가 아닌 +1 00:00:00로 저장
- Resolved : [WUMO-36], [WUMO-400]
[WUMO-36]: https://shoekream.atlassian.net/browse/WUMO-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-400]: https://shoekream.atlassian.net/browse/WUMO-400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-400] Party 수정시 종료일 +1 이슈 해결

src/main/java/org/prgrms/wumo/domain/image/repository/ImageRepository.java
- Image 등록 예외 핸들링 오류 수정
- @Repository로 지정되어 있어 dao 관련 오류로 인식되어 핸들링이 되지 않는 문제 해결
- Resolved : [WUMO-401], [WUMO-406]
[WUMO-401]: https://shoekream.atlassian.net/browse/WUMO-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-406]: https://shoekream.atlassian.net/browse/WUMO-406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-406] Image 등록 예외 핸들링 오류 수정

src/main/java/org/prgrms/wumo/domain/route/api/RouteController.java, src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetAllResponse.java, src/main/java/org/prgrms/wumo/domain/route/dto/response/RouteGetResponse.java, src/main/java/org/prgrms/wumo/global/mapper/RouteMapper.java, src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java
- 루트 상세 조회 end point에서 partyId를 path variable -> request param으로 받도록 수정
해당 도메인의 아이디가 아니기 때문에 partyId를 명시하도록 request param으로 변경했습니다
- 루트 상세 조회 응답시, 루트 이름 데이터도 가도록 수정
- 특이사항은 없습니다
- Resolved : [WUMO-404], [WUMO-405]
[WUMO-404]: https://shoekream.atlassian.net/browse/WUMO-404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-405]: https://shoekream.atlassian.net/browse/WUMO-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-403] Route 상세 조회 리팩토링

src/main/java/org/prgrms/wumo/domain/route/dto/request/RouteRegisterRequest.java, src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java, src/test/java/org/prgrms/wumo/domain/route/api/RouteControllerTest.java, src/test/java/org/prgrms/wumo/domain/route/service/RouteServiceTest.java
- 루트에 후보지 등록 요청 시, 프론트에서 상황에 따라 루트 식별자를 추출하기 어려운 경우가 있어
루트 식별자가 아닌 모임 식별자로 요청하도록 수정하였습니다
- 특이사항은 없습니다
- Resolved : [WUMO-410], [WUMO-411]
[WUMO-410]: https://shoekream.atlassian.net/browse/WUMO-410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WUMO-411]: https://shoekream.atlassian.net/browse/WUMO-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-409] Route에 후보지 등록 기능 리팩토링

src/main/java/org/prgrms/wumo/domain/comment/mapper/CommentMapper.java, src/main/java/org/prgrms/wumo/domain/comment/service/LocationCommentService.java, src/main/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentService.java, src/main/java/org/prgrms/wumo/domain/comment/service/ReplyCommentService.java, src/main/java/org/prgrms/wumo/domain/image/mapper/ImageMapper.java, src/main/java/org/prgrms/wumo/domain/image/service/ImageService.java, src/main/java/org/prgrms/wumo/domain/like/mapper/LikeMapper.java, src/main/java/org/prgrms/wumo/domain/like/service/RouteLikeService.java, src/main/java/org/prgrms/wumo/domain/location/mapper/LocationMapper.java, src/main/java/org/prgrms/wumo/domain/location/service/LocationService.java, src/main/java/org/prgrms/wumo/domain/member/mapper/MemberMapper.java, src/main/java/org/prgrms/wumo/domain/member/service/MemberService.java, src/main/java/org/prgrms/wumo/domain/party/mapper/PartyMapper.java, src/main/java/org/prgrms/wumo/domain/party/service/InvitationService.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyMemberService.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java, src/main/java/org/prgrms/wumo/domain/route/mapper/RouteMapper.java, src/main/java/org/prgrms/wumo/domain/route/service/RouteService.java, src/test/java/org/prgrms/wumo/domain/comment/service/LocationCommentServiceTest.java, src/test/java/org/prgrms/wumo/domain/comment/service/PartyRouteCommentServiceTest.java, src/test/java/org/prgrms/wumo/domain/location/service/LocationServiceTest.java
- 도메인별 mapper 해당 도메인 하위로 패키지 변경
- 팀 회의 결과 mapper를 해당 도메인에서만 사용하기 때문에 global로 빼는것은 불필요하다고 판단하여
해당 도메인 하위로 패키지 수정하였습니다
- 개인적인 생각은 위와 같은 이유로 static keyword가 필요할까 의문이 듭니다
다들 어떻게 생각하시나요??
- Resolved : [WUMO-417]
[WUMO-417]: https://shoekream.atlassian.net/browse/WUMO-417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-416] Mapper 패키지 구조 수정

build.gradle, src/main/java/org/prgrms/wumo/batch/like/RouteLikeBatchComponent.java, src/main/java/org/prgrms/wumo/domain/like/service/RouteLikeService.java, src/test/java/org/prgrms/wumo/domain/like/service/RouteLikeServiceTest.java
- RouteLike 등록 동시성 이슈 해결
- Redisson 분산 락을 활용 -> 특정 루트와 사용자 (ex. "500 150") 를 키로 갖는 락을 점유하여 동시성 이슈 해결
- @Transactional 사용이 불가능하기 때문에 직접 Transaction 제어
- 동시성 이슈를 점검했던 코드의 일부는 여러 테스트에 영향을 줄 수 있어 따로 올리지 않고 아래에 포함하겠습니다.
- Resolved : [WUMO-425]
```java
@Test
void syncTest() throws InterruptedException {
int threadCount = 10;
ExecutorService executorService = Executors.newFixedThreadPool(threadCount);
CountDownLatch latch = new CountDownLatch(threadCount);
for (int i = 0; i < threadCount; i++) {
executorService.execute(() -> {
try {
setAuthentication(member.getId());
routeLikeService.registerRouteLike(route.getId());
} catch (DuplicateException e) {
System.out.println("e = " + e);
}	finally {
latch.countDown();
}});
}
latch.await();
List<Pair<Long, Long>> pairs = …
```
=> [WUMO-425] RouteLike 등록 동시성 이슈 해결

src/main/java/org/prgrms/wumo/domain/comment/listener/LocationCommentListener.java, src/main/java/org/prgrms/wumo/domain/comment/listener/PartyRouteCommentListener.java, src/main/java/org/prgrms/wumo/domain/comment/listener/ReplyCommentListener.java, src/main/java/org/prgrms/wumo/domain/comment/repository/LocationCommentRepository.java, src/main/java/org/prgrms/wumo/domain/comment/repository/PartyRouteCommentRepository.java, src/main/java/org/prgrms/wumo/domain/comment/repository/ReplyCommentRepository.java, src/main/java/org/prgrms/wumo/domain/image/listener/ImageListener.java, src/main/java/org/prgrms/wumo/domain/image/repository/ImageRepository.java, src/main/java/org/prgrms/wumo/domain/like/listener/RouteLikeListener.java, src/main/java/org/prgrms/wumo/domain/like/repository/RouteLikeRepository.java, src/main/java/org/prgrms/wumo/domain/location/listener/LocationListener.java, src/main/java/org/prgrms/wumo/domain/location/repository/LocationRepository.java, src/main/java/org/prgrms/wumo/domain/party/listener/InvitationListener.java, src/main/java/org/prgrms/wumo/domain/party/listener/PartyMemberListener.java, src/main/java/org/prgrms/wumo/domain/party/repository/InvitationRepository.java, src/main/java/org/prgrms/wumo/domain/party/repository/PartyMemberRepository.java, src/main/java/org/prgrms/wumo/domain/party/service/PartyService.java, src/main/java/org/prgrms/wumo/domain/route/listener/RouteListener.java, src/main/java/org/prgrms/wumo/domain/route/repository/RouteRepository.java, src/main/java/org/prgrms/wumo/global/event/listener/EventListenerIntegrator.java, src/main/java/org/prgrms/wumo/global/event/listener/JpaEventListener.java, src/main/resources/META-INF/services/org.hibernate.integrator.spi.Integrator, src/test/java/org/prgrms/wumo/domain/party/service/PartyServiceTest.java
- 전체 도메인 삭제 이벤트 처리
- 회원 탈퇴 유스케이스는 없어서 관련 이벤트 처리는 하지 않았습니다.
- 일부 테스트 중 Image Delete 과정에서 기대하지 않은 값이 오는 경우를 방지하기 위해 null 또는 공백 방지 로직을 추가했습니다.
- Resolved : [WUMO-434]
[WUMO-434]: https://shoekream.atlassian.net/browse/WUMO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WUMO-434] 전체 도메인 삭제 이벤트 처리
